### Keyboard Variables
set $mod Mod4
set $alt Mod1

# Directions using the Keyboard Arrows
set $left Left
set $down Down
set $up Up
set $right Right

### Applications
set $term foot
set $browser zen-browser
set $fmgr thunar

## Workspace Variables
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"