### MX MASTER MOUSE CONFIGURATION
# Button Bindings
bindsym --whole-window $mod+button9 exec $browser
bindsym --whole-window $mod+button8 exec $term
bindcode --whole-window $mod+277 floating toggle

# Side Wheel (Workspace Switching)
bindsym --whole-window $mod+button6 workspace prev
bindsym --whole-window $mod+button7 workspace next

# Central Wheel
bindsym --whole-window $mod+button4 layout toggle tabbed stacking split
bindsym --whole-window $mod+button5 layout toggle split stacking tabbed