### WORKSPACE VARIABLES AND PREFERENCES
## Workspace Names
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

## Default Output Assignments
workspace $ws1 output eDP-1
workspace $ws2 output eDP-1
workspace $ws3 output eDP-1

# Assignments for Work (DP-2) and TV (HDMI-A-1)
workspace $ws4 output DP-2 HDMI-A-1
workspace $ws5 output DP-2 HDMI-A-1
workspace $ws6 output DP-2 HDMI-A-1
workspace $ws7 output DP-2 HDMI-A-1

# Assignments for Work (DP-5) and TV (HDMI-A-1)
workspace $ws8 output DP-5 HDMI-A-1
workspace $ws9 output DP-5 HDMI-A-1
workspace $ws10 output DP-5 HDMI-A-1

# Assignments for Work (DP-2)
workspace $ws4 output DP-2
workspace $ws5 output DP-2
workspace $ws6 output DP-2
workspace $ws7 output DP-2

# Assignments for Work (DP-3)
workspace $ws8 output DP-3
workspace $ws9 output DP-3
workspace $ws10 output DP-3s

## Layout
workspace_layout default